server:
  port: 80
#配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

#微服务连接
zuul:
  routes:
    crowd-portal:
      service-id: crowd-auth
      path: /**
  ignored-services: "*"
  sensitive-headers: "*"
  host:
    connect-timeout-millis: 60000

#熔断超时配置
hystrix:
  command:
    crowd-auth:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
#服务负债均衡配置
crowd-auth:
  ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
#spring应用配置
spring:
  application:
    name: crowd-zuul
  redis:
    host: 101.200.61.176
  session:
    store-type: redis