server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  redis:
    host: 101.200.61.176
  session:
    store-type: redis


#配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
#配置日志打印级别
logging:
  level:
    com.lzc.crowd.controller: debug